name: OpenWorldProject Mac Build
run-name: ${{ github.actor }} is creating a OpenWorldProject mac build
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11.7
      
    - run: git clone https://gitlab.com/kdports/lt-maker.git
    - run: git checkout openworldgamebranch
    - run: cd lt-maker
    - run: python -m pip install -r requirements_engine.txt
    - run: python -m pip install setuptools --upgrade
    - run: cp -R ../OpenWorldProject.ltproj/ OpenWorldProject/
    - run: chmod -R 777 ./*
    - run: ./utilities/build_tools/engine_build.sh OpenWorldProject
    - run: cd ..
    - uses: actions/upload-artifact@v2
      with:
        path: OpenWorldProject/*