name: OpenWorldProject Linux Build
run-name: ${{ github.actor }} is creating a OpenWorldProject linux build
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11.7
      
    - run: |
          git clone https://gitlab.com/kdports/lt-maker.git
          apt-get install dos2unix
          cd lt-maker
          git checkout openworldgamebranch
          pip install pygame-ce==2.3.2
          python -m pip install -r requirements_engine.txt
          python -m pip install setuptools --upgrade
          cp -R ../OpenWorldProject.ltproj/ OpenWorldProject.ltproj/
          chmod -R 777 ./*
          dos2unix ./utilities/build_tools/engine_build.sh
          ./utilities/build_tools/engine_build.sh OpenWorldProject
    - uses: actions/upload-artifact@v2
      with:
        path: OpenWorldProject/*