name: OpenWorldProject Mac Build
run-name: ${{ github.actor }} is creating a OpenWorldProject mac build
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11.7
      
    - run: python -m pip install -r requirements_engine.txt
    - run: python -m pip install setuptools --upgrade
    - run: echo "Prereqs successfully installed"
